id: 47f5cf93b259418b8726ca6007db21e5
title: Toh_97-The_Chapter_on_Manjusri%E2%80%99s_Magical_Display-v1
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-046-003
  eft-text-version: 1.1.4 2021
